### ISSUE TITLE
Incorrect ship requirement

### ISSUE THREAD

**Issue by cprn** [sonejostudios/SpaceNET#10]
IO-11 data sheet lists SD-2 in requirements. SD-2 doesn't have a docking hatch - it should be IO-1.

![image](https://user-images.githubusercontent.com/6132708/115902503-c8f23980-a462-11eb-897d-141824ebfc6f.png)

**Comment by sonejostudios** [comment]
Hi cprn, you are totally right.
I corrected it, thank you! It will be part of the next patch, which will be release in the next days.

All the best,

Vince
